### ISSUE TITLE
Detailed Dataset Preprocessing and Configuration

### ISSUE THREAD

**Issue by JetWings** [CristianoPatricio/coherent-cbe-skin#1]
This is an impressive approach, and I appreciate the author's work. Could you please provide a detailed description of the dataset preprocessing and configuration?

**Comment by CristianoPatricio** [comment]
Hi @JetWings,

Thank you for your interest in our work! You can find all the .CSV files for the dataset splits and dermoscopic concepts [here](https://github.com/CristianoPatricio/coherent-cbe-skin/tree/main/data).

Our approach utilizes a hard attention mechanism based on segmentation masks. We use the DeepLabV3 model trained on HAM10000 to extract segmentation masks for the datasets (PH2 and Derm7pt) in our work, in addition to the ground-truth segmentation masks provided by PH2 and the annotated ones by ours for Derm7pt. The lesion segmentation mask (pre-processing stage of Figure 2) is obtained using i) the extracted binary segmentation mask by DLV3 or ii) the ground-truth segmentation mask provided by the datasets.

Feel free to email me (cristiano.patricio@ubi.pt), and I will send you a link to download all the preprocessed images along with the DLV3 masks.
